### ISSUE TITLE
Needs documentation

### ISSUE THREAD

**Issue by ilhanyumer** [MW-Peachy/Peachy#72]
Few simple examples etc will be enough.

**Comment by Matthewrbowker** [comment]
Note: I will be working on this.

@cyberpower678 Can you assign this issue to me?

**Comment by cyberpower678** [comment]
You need to be made a maintainer.  Would you like to be one?

**Comment by cyberpower678** [comment]
New location is peachy.orain.org

**Comment by Matthewrbowker** [comment]
@cyberpower678 Yes, please.

@ilhanyumer @samwilson I am currently working on the documentation, so that location isn't very complete but in progress.

**Comment by MusikAnimal** [comment]
@cyberpower678 where that link was supposed to go goes to somewhere very inappropriate. What's wrong with the GitHub wiki? Developers know how to use GitHub, and MediaWiki is too heavy for simple docs

**Comment by Matthewrbowker** [comment]
Documentation is now being generated at https://tools.wmflabs.org/peachy-docs/ .  I am working on automating this, but for now these docs are functional.
